name: ESP-IDF Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build_matrix:
    name: Build ${{ matrix.example }} for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [
          "01_gpio_button",
          "02_audio_tone",
          "03_mpu6050_dmp",
          "04_sd_card_basic",
          "05_rgb_led",
          "06_sd_audio_player",
          "07_smart_led"
        ]
        target: [ "esp32s3", "esp32c6" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.4.1'
          target: ${{ matrix.target }}
          path: "examples/${{ matrix.example }}"

  esp32_build_job:
    name: ESP-IDF Final Build Status
    needs: build_matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Matrix Results
        run: |
          if [[ "${{ needs.build_matrix.result }}" != "success" ]]; then
            echo "One or more builds in the matrix failed."
            exit 1
          fi
          echo "All builds passed successfully."
